name: deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cer36/gatsby-gh-pages-action@v1
        with:
          deploy-branch: pages
          gatsby-args: --prefix-paths
          access-token: ${{ secrets.ACCESS_TOKEN }}